version: '3.7'
name : e-commerce

services:
  backend:
    image: master/e-commerce
    # restart : unless-stopped
    user: 1000:1000
    healthcheck:
      test: curl --fail -s http://localhost:80/ >/dev/null || exit 1
      interval: 5s
      timeout: 5s
      retries: 10
    environment:
      - APACHE_RUN_USER=#1000
      - APACHE_RUN_GROUP=#1000
      - DB_HOST=db
      - DB_PORT=5432
      - DB_DATABASE=M1CWA
      - DB_USERNAME=M1CWA
      - DB_PASSWORD=M1CWA
    depends_on:
      db :
        condition: service_healthy
    ports:
      - "51001:80"
    logging:
      options:
        max-size: "10k"
        max-file: "20"
    networks:
      - mcwa
  
  db:
    image: postgres:14-alpine
    healthcheck:
      test: pg_isready -U M1CWA || exit 1
      interval: 5s
      timeout: 5s
      retries: 10
    ports:
      - 56788:5432
    volumes:
      - mcwa-data:/var/lib/postgresql/data
    environment:
      TZ: Europe/Paris
      POSTGRES_INITDB_ARGS: --encoding=UTF-8 --lc-collate=fr_FR.UTF-8 --lc-ctype=fr_FR.UTF-8
      PGDATA: /var/lib/postgresql/data
      POSTGRES_DB: M1CWA
      POSTGRES_USER: M1CWA
      POSTGRES_PASSWORD: M1CWA
      SERVICE_TAGS: dev
      SERVICE_NAME: pgsql 
    logging:
      options:
        max-size: "10k"
        max-file: "20"
    networks:
      - mcwa

volumes:
    mcwa-data:

networks:
    mcwa:
      driver: bridge
      name: 'mcwa'
